export const config = {
  questions: [
    {
      question: "¿Cual es tu nombre?",
      name: "Question 1",
      code: "question1",
      type: "text",
      placeholder: "Escribe tu nombre",
      page: 1,
    },
    {
      question: "¿Cual es tu edad?",
      name: "Question 2",
      code: "question2",
      type: "number",
      placeholder: "Escribe cuantos años tienes",
      page: 1,
    },
    {
      question: "¿Cual es tu grado academico?",
      name: "Question 3",
      code: "question3",
      type: "text",
      placeholder: "Escribe si tu nivel academico es primario, medio, etc",
      page: 1,
    },
    {
      question: "¿Te gusta escuchar musica?",
      name: "Question 4",
      code: "question4",
      type: "text",
      placeholder: "Escribe Si o No",
      page: 2,
    },
    {
      question: "Si la tienes, ¿Cual es tu apliacion favorita para escuchar musica?",
      name: "Question 5",
      code: "question5",
      type: "text",
      placeholder: "Escribe el nombre de tu aplicacion preferida",
      page: 2,
    },
    {
      question: "¿Que tan frecuentemente escuchas musica?",
      name: "Question 6",
      code: "question6",
      type: "text",
      placeholder: "Escribe la frecuencia con la que escuchas musica",
      page: 2,
    },
    {
      question: "¿Te gustaria aprender a hacer musica?",
      name: "Question 7",
      code: "question7",
      type: "text",
      placeholder: "Escribe Si o No",
      page: 3,
    },
    {
      question: "¿Te gustaria aprender a tocar un instrumento?",
      name: "Question 8",
      code: "question8",
      type: "text",
      placeholder: "Escribe Si o No",
      page: 3,
    },
    {
      question: "¿Has estado en una banda anteriormente?",
      name: "question 9",
      code: "question9",
      type: "text",
      placeholder: "Escribe Si o No",
      page: 3,
    },
    {
      question: "¿Te gustaria escribir la letra de una cancion?",
      name: "question 10",
      code: "question10",
      type: "text",
      placeholder: "Escribe Si o No",
      page: 4,
    },
    {
      question: "¿Te gusta ir a conciertos?",
      name: "question 11",
      code: "question11",
      type: "text",
      placeholder: "Escribe Si o No",
      page: 4,
    },
    {
      question: "¿Sueles escuchar podcasts?",
      name: "question 12",
      code: "question12",
      type: "text",
      placeholder: "Escribe Si o No",
      page: 4,
    },
    {
      question: "¿Te gusta escuchar musica mientras trabajas?",
      name: "question 13",
      code: "question13",
      type: "text",
      placeholder: "Escribe Si o No",
      page: 5,
    },
    {
      question: "¿Cual es el genero musical que mas te gusta?",
      name: "question 14",
      code: "question14",
      type: "text",
      placeholder: "Escribe el nombre de tu genero musical favorito",
      page: 5,
    },
    {
      question: "¿Cual es tu artista favorito?",
      name: "question 15",
      code: "question15",
      type: "text",
      placeholder: "Escribe el nombre de tu artista favorito",
      page:5,
    },
  ]
};
